from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
manifest_path = ROOT / 'GOLD_CONTROL_PROJECT_MANIFEST.md'
stage4_path = ROOT / 'GOLD_CONTROL_STAGE4_STATUS_2026-09-01.md'
forecast_path = ROOT / 'GOLD_CONTROL_FORECAST_CANONICALIZATION.md'
audit_path = ROOT / 'GOLD_CONTROL_STAGE4_FORECAST_ISSUANCE_AUDIT_2026-09-01.md'

manifest = manifest_path.read_text(encoding='utf-8')
if '**Manifest version:** 1.7' not in manifest:
    raise SystemExit('EXPECTED_MANIFEST_V1_7_NOT_FOUND')
manifest = manifest.replace('**Manifest version:** 1.7', '**Manifest version:** 1.8', 1)

old_row = '| 4 | `IN_PROGRESS_BLOCKED_FORECAST_ISSUANCE` | Deterministic engine/bridge tests PASS. Canonical `XAU_EOD_TWELVE_NY17` access, mapping and Neon ingestion are PASS. Remaining blockers are the first genuine immutable H=1 forecast input snapshot and monthly forecast contract |'
new_row = '| 4 | `IN_PROGRESS_BLOCKED_FORECAST_AND_MONTHLY_CONTEXT` | Deterministic engine/bridge tests PASS and latest canonical NY17 ingestion PASS. Deeper audit proves current Patch issuer is only frozen through the August target, exact VW production runner remains `BLOCKED_NOT_PROVEN`, R4.1 monthly VW/direction inputs are not issued, forecast snapshot/contract tables are empty, and canonical NY17 history backfill is not yet successful |'
if old_row not in manifest:
    raise SystemExit('STAGE4_ROADMAP_ROW_NOT_FOUND')
manifest = manifest.replace(old_row, new_row, 1)

old_blockers = '''Confirmed active blockers after manifest v1.7 XAU pipeline closure:\n\n1. `FORECAST_CONTRACT_NOT_ISSUED`\n2. `IMMUTABLE_FORECAST_INPUT_SNAPSHOT_NOT_ISSUED`\n'''
new_blockers = '''Confirmed active blockers after manifest v1.8 dependency audit:\n\n1. `IMMUTABLE_FORECAST_INPUT_SNAPSHOT_NOT_ISSUED`\n2. `FORECAST_CONTRACT_NOT_ISSUED`\n3. `PATCH_R1_CURRENT_ISSUER_NOT_PROVEN`\n   - the retained executable runner is hard-coded to the August 2026 target / July 2026 input horizon; no September issuer is frozen by evidence.\n4. `VW_CURRENT_MONTHLY_REFERENCE_NOT_ISSUED`\n   - `VW_EXECUTABLE_REPRODUCTION_BLOCKED_NOT_PROVEN`; the exact original VW-MIDAS-SVR Adapt V2 runner/source chain is not retained.\n5. `MONTHLY_DIRECTION_CONTEXT_NOT_ISSUED`\n   - R4.1 requires a frozen monthly direction input; it may not be inferred ad hoc by the app or daily issuer.\n6. `CANONICAL_XAU_HISTORY_BACKFILL_NOT_YET_SUCCESS`\n   - one canonical NY17 production observation exists, but Fast/Slow and 3M monthly context require a longer same-lineage history. A PIT-safe backfill is being validated; historical rows retain current retrieval-time availability and are never relabelled as historically knowable.\n'''
if old_blockers not in manifest:
    raise SystemExit('BLOCKERS_ANCHOR_NOT_FOUND')
manifest = manifest.replace(old_blockers, new_blockers, 1)

old_gates = '''Required next gates, in order:\n\n1. create the first genuine immutable H=1 forecast input snapshot from the executable frozen forecasting path using only data point-in-time available at the issuance origin;\n2. issue the matching monthly forecast contract binding target definition, executable Patch R1 point forecast, audited VW reference, RW benchmark, 3M direction context, model/code version, input snapshot id and issued-at timestamp;\n3. verify the new snapshot/contract rows in Neon before outcome realization;\n4. only then build/schedule the canonical R4.1 EOD issuer using the frozen engine and complete provenance;\n5. the first real forward decision state must begin as `PROSPECTIVE_SHADOW`; `LIVE_PRODUCTION` remains disabled until Stage 12 graduation;\n6. do not backfill historical rows and relabel them as prospective.\n'''
new_gates = '''Required next gates, in order:\n\n1. complete and verify PIT-safe same-lineage `XAU_EOD_TWELVE_NY17` history sufficient for frozen Fast/Slow and 3M monthly-context construction; backfilled rows use current retrieval-time availability and do not become retroactively knowable;\n2. resolve the R4.1 monthly price-reference path without silent model substitution: either recover/prove the exact VW-MIDAS-SVR Adapt V2 executable identity, or run a separately governed architecture change with frozen pre-prospective validation before replacing that role;\n3. freeze and issue the monthly direction context under the existing 3M Momentum role from the approved same-lineage input contract;\n4. resolve the current H=1 executable point issuer: Patch R1 may not be date-extended beyond its proven August horizon by editing constants; a successor/bridge requires explicit change control and leakage-safe evidence;\n5. only after the chosen executable forecast path is proven, create the first genuine immutable input snapshot and matching monthly forecast contract with actual issuance timestamp and complete provenance;\n6. verify forecast/monthly-context rows in Neon before target outcome realization;\n7. only then build/schedule the canonical R4.1 EOD issuer; first forward decision state = `PROSPECTIVE_SHADOW`, never retroactive and not `LIVE_PRODUCTION`.\n'''
if old_gates not in manifest:
    raise SystemExit('NEXT_GATES_ANCHOR_NOT_FOUND')
manifest = manifest.replace(old_gates, new_gates, 1)

insert_anchor = 'No `PROSPECTIVE_SHADOW` or `LIVE_PRODUCTION` decision row may be written while any active Stage-4 readiness blocker remains open.\n'
insert_text = insert_anchor + '''\n### Manifest v1.8 forecast/monthly-context dependency audit\n\nEvidence:\n\n- live forecast-state schema audit: GitHub Actions run `33512445624`, job `99871192709`, `SUCCESS`, read-only Neon transaction; all three forecast-state tables existed and each had 0 rows;\n- retained Patch input package ended at `core5` month `2026-07-01`; retained Patch runners contain July/August horizon constants, therefore `PATCH_R1_CURRENT_ISSUER_NOT_PROVEN`;\n- canonical-history forensic: run `33513175499`, job `99873596626`, `SUCCESS`; exact original VW-MIDAS-SVR Adapt V2 runner/source chain was not recovered from reachable canonical history; rebuild scripts exist but are explicitly reconstruction/research paths, not identity proof;\n- `r4_1/contracts.py` requires both `monthly_vw_forecast` and `monthly_direction` in every `EngineSnapshot`; neither may be silently replaced with RW/Patch/live spot;\n- NY17 history-depth probe run `33513634775`, job `99875100590`, `SUCCESS`, proves exact 16:59 ET Twelve bars are accessible from May through August 2026 on sampled dates, but the first atomic July-August backfill run `33512957983`, job `99872871327`, failed before persistence due transient provider/request errors.\n\nCanonical audit record: `gold_axis_2026/GOLD_CONTROL_STAGE4_FORECAST_ISSUANCE_AUDIT_2026-09-01.md`.\n'''
if insert_anchor not in manifest:
    raise SystemExit('INSERT_ANCHOR_NOT_FOUND')
manifest = manifest.replace(insert_anchor, insert_text, 1)
manifest_path.write_text(manifest, encoding='utf-8')

stage4 = stage4_path.read_text(encoding='utf-8')
stage4 = stage4.replace('**Manifest:** `GOLD_CONTROL_PROJECT_MANIFEST.md` v1.7', '**Manifest:** `GOLD_CONTROL_PROJECT_MANIFEST.md` v1.8', 1)
stage4 = stage4.replace('**Current status:** `IN_PROGRESS_BLOCKED_FORECAST_ISSUANCE`', '**Current status:** `IN_PROGRESS_BLOCKED_FORECAST_AND_MONTHLY_CONTEXT`', 1)
old_s = '''## 5. Active readiness blockers\n\n1. `FORECAST_CONTRACT_NOT_ISSUED`\n2. `IMMUTABLE_FORECAST_INPUT_SNAPSHOT_NOT_ISSUED`\n\nClosed by canonical production-ingestion run `33511805110`, job `99869043161`:\n\n`TWELVE_XAU_NY17_PIPELINE_NOT_SUCCESS` → `CLOSED`\n\nThe run wrote one `XAU_EOD_TWELVE_NY17` observation for completed trade date `2026-08-31` at `2026-08-31T21:00:00+00:00`, with source `Twelve Data`, quality `APPROVED_CANONICAL_TWELVE_NY17`, retrieval status `SUCCESS`, zero quality errors and no raw market-price logging.\n'''
new_s = '''## 5. Active readiness blockers — manifest v1.8\n\n1. `IMMUTABLE_FORECAST_INPUT_SNAPSHOT_NOT_ISSUED`\n2. `FORECAST_CONTRACT_NOT_ISSUED`\n3. `PATCH_R1_CURRENT_ISSUER_NOT_PROVEN`\n4. `VW_CURRENT_MONTHLY_REFERENCE_NOT_ISSUED` / `VW_EXECUTABLE_REPRODUCTION_BLOCKED_NOT_PROVEN`\n5. `MONTHLY_DIRECTION_CONTEXT_NOT_ISSUED`\n6. `CANONICAL_XAU_HISTORY_BACKFILL_NOT_YET_SUCCESS`\n\nThe latest single-day canonical production ingestion remains `SUCCESS` by run `33511805110`, job `99869043161`; the new history blocker is distinct from that daily-pipeline success and exists because R4.1 Fast/Slow/3M context require longer same-lineage history.\n'''
if old_s not in stage4:
    raise SystemExit('STAGE4_BLOCKER_SECTION_NOT_FOUND')
stage4 = stage4.replace(old_s, new_s, 1)
old_next = '''## 6. Required next work\n\n1. inspect the live Neon forecast-state table contract and executable Patch R1 issuance path;\n2. create the first genuine immutable H=1 forecast input snapshot using point-in-time available inputs only;\n3. issue the matching monthly forecast contract before target outcome realization and verify both rows in Neon;\n4. build/schedule the canonical R4.1 EOD issuer only after those inputs pass;\n5. first forward Decision Store state = `PROSPECTIVE_SHADOW`, never retroactive and not `LIVE_PRODUCTION`.\n'''
new_next = '''## 6. Required next work\n\n1. complete PIT-safe NY17 history backfill and verify sufficient Fast/Slow/monthly-context coverage;\n2. keep exact VW identity `BLOCKED_NOT_PROVEN` unless identity is actually recovered; do not promote rebuild scripts by name similarity;\n3. resolve/freeze the current monthly VW reference and 3M direction issuance contracts;\n4. resolve the current H=1 executable issuer without extending Patch constants beyond their proven horizon by assumption;\n5. only then persist the first immutable forecast input snapshot + monthly forecast contract and verify in Neon;\n6. build/schedule canonical R4.1 issuer only after all mandatory `EngineSnapshot` inputs exist; first forward Decision Store state = `PROSPECTIVE_SHADOW`.\n'''
if old_next not in stage4:
    raise SystemExit('STAGE4_NEXT_SECTION_NOT_FOUND')
stage4 = stage4.replace(old_next, new_next, 1)
stage4 += '''\n\n## 7. Forecast/monthly-context audit evidence\n\n- forecast schema/horizon audit: run `33512445624`, job `99871192709`, `SUCCESS`; DB read-only; forecast-state row counts all zero; `core5` ends July 2026 and retained Patch runner is August-horizon specific.\n- VW canonical-history forensic: run `33513175499`, job `99873596626`, `SUCCESS`; exact original VW runner/source chain `NOT_FOUND` in reachable canonical history; existing rebuild scripts do not close identity provenance.\n- NY17 May-Aug depth probe: run `33513634775`, job `99875100590`, `SUCCESS`; sampled exact bars available.\n- first atomic Jul-Aug history backfill: run `33512957983`, job `99872871327`, `FAILURE` before persistence because provider/request errors remained; no partial write was authorized by the backfill code.\n'''
stage4_path.write_text(stage4, encoding='utf-8')

forecast = forecast_path.read_text(encoding='utf-8')
if '**Canonicalization version:** 1.1' in forecast:
    forecast = forecast.replace('**Canonicalization version:** 1.1', '**Canonicalization version:** 1.2', 1)
forecast += '''\n\n---\n\n# 12. 2026-09-01 CURRENT-ISSUER AUDIT — MANIFEST V1.8\n\nThe historical production-closure role registry remains unchanged, but executability must be separated from **current issuance readiness**.\n\n## Patch R1\n\nThe retained executable artifacts prove the historical/closure Patch path through the August 2026 target. The live code audit found `core5_monthly` ending at `2026-07-01`, an August target constant in `run_august_2026.py`, and July cutoffs in retained model code. No audited September-2026 issuer contract was found.\n\nStatus: `PATCH_R1_CURRENT_ISSUER_NOT_PROVEN`.\n\nThis does not revoke the historical `PATCH_R1_EXECUTABLE` role inside the production-closure package; it prohibits silently date-extending that role into a new prospective target.\n\n## VW-MIDAS-SVR Adapt V2\n\nCanonical reachable-history forensic run `33513175499` found rebuild/research scripts but did not recover the exact original immutable production runner/source preprocessing chain. `r4_1/KNOWN_BLOCKERS.md` and `PROVENANCE.json` already classify exact reproduction as blocked.\n\nStatus: `VW_EXECUTABLE_REPRODUCTION_BLOCKED_NOT_PROVEN`.\n\nR4.1 nevertheless requires a numeric `monthly_vw_forecast` input. Therefore Stage 4 cannot silently substitute Patch, RW, a rebuild, or live spot into that field. Recovery of exact identity or an explicit separately validated architecture change is required.\n\n## Forecast ledger\n\nRead-only Neon audit run `33512445624`, job `99871192709`, confirmed `forecast_input_snapshots`, `derived_feature_snapshots`, and `monthly_forecast_contracts` all exist and all remain empty. No row may be created merely to satisfy a readiness count without a valid executable issuance path.\n'''
forecast_path.write_text(forecast, encoding='utf-8')

audit = '''# GOLD CONTROL — STAGE 4 FORECAST / MONTHLY-CONTEXT ISSUANCE AUDIT\n\n**Audit date:** 2026-09-01  \n**Manifest:** target v1.8  \n**Decision:** `BLOCKED_WITH_EXPLICIT_CURRENT_ISSUER_AND_MONTHLY_CONTEXT_GAPS`\n\n## Executive conclusion\n\nThe canonical daily NY17 source is operational, but Stage 4 is not yet ready for a prospective R4.1 decision because the mandatory monthly model/context inputs and the H=1 current issuer are not all executable/issued under proven contracts.\n\n## Evidence\n\n### Live forecast-state schema\n\nGitHub Actions run `33512445624`, job `99871192709`, `SUCCESS`, used a read-only Neon transaction. All three forecast-state tables exist and contain zero rows.\n\n### Patch current issuer\n\n`core5_monthly` ends at `2026-07-01`. Retained Patch operational code is August-2026 specific and contains July cutoffs. Historical Patch closure executability is not evidence of a September issuer.\n\nStatus: `PATCH_R1_CURRENT_ISSUER_NOT_PROVEN`.\n\n### VW current R4.1 reference\n\nR4.1 `EngineSnapshot` requires `monthly_vw_forecast`. Canonical-history forensic run `33513175499`, job `99873596626`, did not recover the exact original VW-MIDAS-SVR Adapt V2 runner/source chain. Existing `run_vw_*` files are reconstruction/research artifacts and the retained VW rebuild code itself treats exact replication as blocked.\n\nStatus: `VW_EXECUTABLE_REPRODUCTION_BLOCKED_NOT_PROVEN`; `VW_CURRENT_MONTHLY_REFERENCE_NOT_ISSUED`.\n\n### Monthly direction context\n\nR4.1 also requires `monthly_direction`. The frozen role remains 3M Momentum; no prospective monthly-direction issuance row exists.\n\nStatus: `MONTHLY_DIRECTION_CONTEXT_NOT_ISSUED`.\n\n### Canonical NY17 history\n\nThe single-day canonical daily pipeline passed. For Fast/Slow and 3M direction, longer same-lineage history is required. Sampled Twelve exact NY17 history is available from May-August (run `33513634775`, job `99875100590`, `SUCCESS`). The first atomic July-August backfill run `33512957983`, job `99872871327`, failed before persistence because seven provider/request errors remained. The code did not authorize a partial write.\n\nStatus: `CANONICAL_XAU_HISTORY_BACKFILL_NOT_YET_SUCCESS`.\n\n## Governance decision\n\n- do not backdate an issuance timestamp to 2026-08-31 for data first retrieved on 2026-09-01;\n- do not label backfilled NY17 observations as historically knowable before their recorded retrieval time;\n- do not extend Patch by changing date constants and call it the frozen production model;\n- do not promote VW reconstruction scripts as the exact audited VW identity without output/source-chain identity proof;\n- do not use RW/Patch/live spot as a silent replacement for `monthly_vw_forecast`;\n- do not create forecast-table rows solely to clear readiness gates.\n\nThe first legitimate forward decision remains `PROSPECTIVE_SHADOW` only after all required R4.1 snapshot inputs are issued with immutable provenance.\n'''
audit_path.write_text(audit, encoding='utf-8')

print('GOLD_CONTROL_STAGE4_FORECAST_AUDIT_V1_8_PASS')
