-- GOLD_CONTROL_MULTI_EXPERT_FORECAST_V1
-- Manifest v1.22: build experts first, select later.
-- Individual expert rows are NEVER canonical selector/ensemble authority.

CREATE TABLE IF NOT EXISTS monthly_expert_forecasts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_month date NOT NULL,
    forecast_origin timestamptz NOT NULL,
    as_of timestamptz NOT NULL,
    forecast_track text NOT NULL CHECK (forecast_track IN ('MONTH_END_EXPERT', 'EARLY_INDICATIVE')),
    expert_id text NOT NULL CHECK (expert_id IN ('CAUSAL_PATCH', 'VW_MIDAS_MSVR', 'MOMENTUM_3M', 'RANDOM_WALK')),
    model_name text NOT NULL,
    model_version text NOT NULL,
    expert_role text NOT NULL CHECK (expert_role IN ('EXPERT', 'BENCHMARK')),
    forecast_value double precision NOT NULL CHECK (forecast_value > 0),
    unit text NOT NULL DEFAULT 'USD/oz',
    evidence_class text NOT NULL CHECK (evidence_class IN ('PROSPECTIVE_SHADOW', 'LIVE_PRODUCTION')),
    git_commit text,
    input_snapshot_ids bigint[] NOT NULL CHECK (cardinality(input_snapshot_ids) > 0),
    input_fingerprint text NOT NULL CHECK (length(input_fingerprint) > 0),
    selector_status text NOT NULL DEFAULT 'NOT_PROVEN_EXPERT_SELECTION_RULE'
        CHECK (selector_status = 'NOT_PROVEN_EXPERT_SELECTION_RULE'),
    auto_selector text NOT NULL DEFAULT 'OFF' CHECK (auto_selector = 'OFF'),
    auto_ensemble text NOT NULL DEFAULT 'OFF' CHECK (auto_ensemble = 'OFF'),
    canonical_authority boolean NOT NULL DEFAULT false CHECK (canonical_authority = false),
    provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (target_month, forecast_track, as_of, expert_id, model_version)
);

CREATE INDEX IF NOT EXISTS monthly_expert_target_track_idx
    ON monthly_expert_forecasts (target_month DESC, forecast_track, as_of DESC);

CREATE INDEX IF NOT EXISTS monthly_expert_identity_idx
    ON monthly_expert_forecasts (expert_id, model_version, as_of DESC);

CREATE INDEX IF NOT EXISTS monthly_expert_evidence_idx
    ON monthly_expert_forecasts (evidence_class, target_month DESC, as_of DESC);

DO $$
BEGIN
    IF to_regprocedure('reject_gold_control_forecast_state_mutation()') IS NULL THEN
        RAISE EXCEPTION 'BLOCKED_FORECAST_IMMUTABILITY_GUARD_NOT_FOUND';
    END IF;
END
$$;

DROP TRIGGER IF EXISTS trg_monthly_expert_forecasts_immutable ON monthly_expert_forecasts;
CREATE TRIGGER trg_monthly_expert_forecasts_immutable
BEFORE UPDATE OR DELETE ON monthly_expert_forecasts
FOR EACH ROW EXECUTE FUNCTION reject_gold_control_forecast_state_mutation();

COMMENT ON TABLE monthly_expert_forecasts IS
'Manifest v1.22 append-only individual expert ledger. MONTH_END_EXPERT and EARLY_INDICATIVE are separate tracks. Individual rows have canonical_authority=false; selector and ensemble remain OFF until separately frozen change-control.';
