-- Gold Data R1 private storage schema
-- Designed for Supabase/Postgres. Raw observations are append-only.

create table if not exists retrieval_runs (
  run_id uuid primary key,
  started_at timestamptz not null,
  finished_at timestamptz,
  git_sha text,
  pipeline_version text not null,
  status text not null,
  notes text
);

create table if not exists observations (
  id bigint generated by default as identity primary key,
  run_id uuid not null references retrieval_runs(run_id),
  series_id text not null,
  observation_ts timestamptz not null,
  value double precision not null,
  source text not null,
  source_symbol text,
  provider_as_of timestamptz,
  retrieved_at timestamptz not null,
  frequency text not null,
  unit text,
  transform text not null default 'LEVEL',
  quality_status text not null,
  lineage_id text not null,
  payload_hash text,
  metadata jsonb not null default '{}'::jsonb,
  unique(series_id, observation_ts, retrieved_at, lineage_id)
);

create index if not exists observations_series_ts_idx
  on observations(series_id, observation_ts desc);
create index if not exists observations_retrieved_idx
  on observations(retrieved_at desc);
create index if not exists observations_lineage_idx
  on observations(lineage_id, series_id, observation_ts desc);

-- The latest retrieval for each observation date; revisions remain in observations.
create or replace view canonical_latest as
select distinct on (series_id, observation_ts, lineage_id)
  series_id, observation_ts, value, source, source_symbol, provider_as_of,
  retrieved_at, frequency, unit, transform, quality_status, lineage_id,
  metadata
from observations
order by series_id, observation_ts, lineage_id, retrieved_at desc, id desc;

-- Latest available point for dashboard cards.
create or replace view latest_series as
select distinct on (series_id, lineage_id)
  series_id, observation_ts, value, source, source_symbol, provider_as_of,
  retrieved_at, frequency, unit, transform, quality_status, lineage_id,
  metadata
from canonical_latest
order by series_id, lineage_id, observation_ts desc, retrieved_at desc;

-- Store complete revision-prone source files/vintages by hash, without overwriting.
create table if not exists source_vintages (
  vintage_id bigint generated by default as identity primary key,
  source_id text not null,
  retrieved_at timestamptz not null,
  provider_as_of timestamptz,
  content_sha256 text not null,
  content_type text,
  byte_count bigint,
  metadata jsonb not null default '{}'::jsonb,
  unique(source_id, content_sha256)
);

-- Quality events are separate from observations so bad retrievals leave an audit trail.
create table if not exists quality_events (
  id bigint generated by default as identity primary key,
  run_id uuid references retrieval_runs(run_id),
  series_id text,
  event_ts timestamptz not null,
  severity text not null,
  code text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb
);
